# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mapreduce_pb2 as mapreduce__pb2


class JobServiceStub(object):
    """Client-Coordinator service for job submission and management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/mapreduce.JobService/SubmitJob',
                request_serializer=mapreduce__pb2.JobSpec.SerializeToString,
                response_deserializer=mapreduce__pb2.JobResponse.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/mapreduce.JobService/GetJobStatus',
                request_serializer=mapreduce__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.JobStatusResponse.FromString,
                )
        self.GetJobResult = channel.unary_unary(
                '/mapreduce.JobService/GetJobResult',
                request_serializer=mapreduce__pb2.JobResultRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.JobResultResponse.FromString,
                )


class JobServiceServicer(object):
    """Client-Coordinator service for job submission and management
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=mapreduce__pb2.JobSpec.FromString,
                    response_serializer=mapreduce__pb2.JobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=mapreduce__pb2.JobStatusRequest.FromString,
                    response_serializer=mapreduce__pb2.JobStatusResponse.SerializeToString,
            ),
            'GetJobResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobResult,
                    request_deserializer=mapreduce__pb2.JobResultRequest.FromString,
                    response_serializer=mapreduce__pb2.JobResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Client-Coordinator service for job submission and management
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.JobService/SubmitJob',
            mapreduce__pb2.JobSpec.SerializeToString,
            mapreduce__pb2.JobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.JobService/GetJobStatus',
            mapreduce__pb2.JobStatusRequest.SerializeToString,
            mapreduce__pb2.JobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.JobService/GetJobResult',
            mapreduce__pb2.JobResultRequest.SerializeToString,
            mapreduce__pb2.JobResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TaskServiceStub(object):
    """Coordinator-Worker service for task assignment and health monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AssignMapTask = channel.unary_unary(
                '/mapreduce.TaskService/AssignMapTask',
                request_serializer=mapreduce__pb2.MapTaskRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.TaskResult.FromString,
                )
        self.AssignReduceTask = channel.unary_unary(
                '/mapreduce.TaskService/AssignReduceTask',
                request_serializer=mapreduce__pb2.ReduceTaskRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.TaskResult.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/mapreduce.TaskService/Heartbeat',
                request_serializer=mapreduce__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.WorkerStatus.FromString,
                )


class TaskServiceServicer(object):
    """Coordinator-Worker service for task assignment and health monitoring
    """

    def AssignMapTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignReduceTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AssignMapTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignMapTask,
                    request_deserializer=mapreduce__pb2.MapTaskRequest.FromString,
                    response_serializer=mapreduce__pb2.TaskResult.SerializeToString,
            ),
            'AssignReduceTask': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignReduceTask,
                    request_deserializer=mapreduce__pb2.ReduceTaskRequest.FromString,
                    response_serializer=mapreduce__pb2.TaskResult.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mapreduce__pb2.HeartbeatRequest.FromString,
                    response_serializer=mapreduce__pb2.WorkerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Coordinator-Worker service for task assignment and health monitoring
    """

    @staticmethod
    def AssignMapTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.TaskService/AssignMapTask',
            mapreduce__pb2.MapTaskRequest.SerializeToString,
            mapreduce__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignReduceTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.TaskService/AssignReduceTask',
            mapreduce__pb2.ReduceTaskRequest.SerializeToString,
            mapreduce__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.TaskService/Heartbeat',
            mapreduce__pb2.HeartbeatRequest.SerializeToString,
            mapreduce__pb2.WorkerStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
