# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\tmapreduce\"}\n\nJobRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\x12\x15\n\rjob_file_path\x18\x03 \x01(\t\x12\x15\n\rnum_map_tasks\x18\x04 \x01(\x05\x12\x18\n\x10num_reduce_tasks\x18\x05 \x01(\x05\"-\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\"\n\x10JobStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"\xbc\x01\n\x11JobStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x17\n\x0ftotal_map_tasks\x18\x03 \x01(\x05\x12\x1b\n\x13\x63ompleted_map_tasks\x18\x04 \x01(\x05\x12\x1a\n\x12total_reduce_tasks\x18\x05 \x01(\x05\x12\x1e\n\x16\x63ompleted_reduce_tasks\x18\x06 \x01(\x05\x12\x15\n\rerror_message\x18\x07 \x01(\t\"\x07\n\x05\x45mpty\"3\n\x0fJobListResponse\x12 \n\x04jobs\x18\x01 \x03(\x0b\x32\x12.mapreduce.JobInfo\">\n\x07JobInfo\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bsubmit_time\x18\x03 \x01(\t\"#\n\x11JobResultsRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"J\n\x12JobResultsResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0coutput_files\x18\x03 \x03(\t2\xa3\x02\n\x12\x43oordinatorService\x12:\n\tSubmitJob\x12\x15.mapreduce.JobRequest\x1a\x16.mapreduce.JobResponse\x12I\n\x0cGetJobStatus\x12\x1b.mapreduce.JobStatusRequest\x1a\x1c.mapreduce.JobStatusResponse\x12\x38\n\x08ListJobs\x12\x10.mapreduce.Empty\x1a\x1a.mapreduce.JobListResponse\x12L\n\rGetJobResults\x12\x1c.mapreduce.JobResultsRequest\x1a\x1d.mapreduce.JobResultsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOBREQUEST']._serialized_start=32
  _globals['_JOBREQUEST']._serialized_end=157
  _globals['_JOBRESPONSE']._serialized_start=159
  _globals['_JOBRESPONSE']._serialized_end=204
  _globals['_JOBSTATUSREQUEST']._serialized_start=206
  _globals['_JOBSTATUSREQUEST']._serialized_end=240
  _globals['_JOBSTATUSRESPONSE']._serialized_start=243
  _globals['_JOBSTATUSRESPONSE']._serialized_end=431
  _globals['_EMPTY']._serialized_start=433
  _globals['_EMPTY']._serialized_end=440
  _globals['_JOBLISTRESPONSE']._serialized_start=442
  _globals['_JOBLISTRESPONSE']._serialized_end=493
  _globals['_JOBINFO']._serialized_start=495
  _globals['_JOBINFO']._serialized_end=557
  _globals['_JOBRESULTSREQUEST']._serialized_start=559
  _globals['_JOBRESULTSREQUEST']._serialized_end=594
  _globals['_JOBRESULTSRESPONSE']._serialized_start=596
  _globals['_JOBRESULTSRESPONSE']._serialized_end=670
  _globals['_COORDINATORSERVICE']._serialized_start=673
  _globals['_COORDINATORSERVICE']._serialized_end=964
# @@protoc_insertion_point(module_scope)
